apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ofbiz.fullname" . }}
  labels:
    {{- include "ofbiz.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ofbiz.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ofbiz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ofbiz.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ofbiz.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: runtime
        persistentVolumeClaim:
          claimName: {{ include "ofbiz.fullname" . }}-runtime
      - name: configmap
        configMap:
          name: {{ include "ofbiz.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: runtime
            mountPath: /opt/ofbiz/runtime
          volumeMounts:
          - name: configmap
            mountPath: /opt/ofbiz/config
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: accounting/control/login
          #     port: http
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          # readinessProbe:
          #   httpGet:
          #     path: accounting/control/login
          #     port: http
          #   initialDelaySeconds: 35
          #   periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
